In [1]:
%load_ext autoreload
%autoreload 2
%matplotlib inline
%cd ..

/home/sven/Developer/pycharm/kaggle-earthquake-prediction

In [4]:
from collections import defaultdict

from earthquake_prediction.utils import read_test
from earthquake_prediction.experiments import cnn_encoder_lstm

import torch
import pandas as pd

In [13]:
exp = cnn_encoder_lstm.Experiment('lstm2', pd.DataFrame([]))
exp.load()

In [7]:
test_files = read_test()

In [14]:
results = defaultdict(list)

for name, inp in test_files:
    pred = exp.predict(torch.from_numpy(inp['acoustic_data'].values).unsqueeze(0).unsqueeze(0).float())
    results['seg_id'].append(name)
    results['time_to_failure'].append(pred)

In [16]:
res = pd.DataFrame(results)
# len(res[res['time_to_failure'] < 3])
res

          seg_id  time_to_failure
0     seg_a16a1b         6.877479
1     seg_4c8db6         8.392071
2     seg_816b7a         6.186820
3     seg_82316b         7.002635
4     seg_7c0376         6.827004
5     seg_20cbac         8.420543
6     seg_8244bf         8.374791
7     seg_168d1c         8.315585
8     seg_5255c0         8.425346
9     seg_3af649         8.376569
10    seg_1c4c5b         8.365093
11    seg_95f45e         7.854548
12    seg_49fdf0         8.199512
13    seg_cedf3e         8.405365
14    seg_a0979e         8.248280
15    seg_950048         8.331847
16    seg_046c28         8.364244
17    seg_9a8a1f         6.185168
18    seg_502fab         8.371697
19    seg_cf1371         6.889911
20    seg_ba9dbf         6.583304
21    seg_b95010         8.341825
22    seg_a543e5         8.176996
23    seg_fb00b3         8.112627
24    seg_f9eea3         8.417364
25    seg_355d19         8.427924
26    seg_68102c         6.448992
27    seg_61219c         7.878785
28    seg_eb7f91         8.421859
29    seg_8b798b         7.416499
...          ...              ...
2594  seg_7211f1         8.414206
2595  seg_4b0839         6.846225
2596  seg_a31d6e         7.733625
2597  seg_c0c0ed         8.262614
2598  seg_a86a05         8.438059
2599  seg_2916e3         8.380200
2600  seg_e877a5         8.427142
2601  seg_b0f9cd         7.907629
2602  seg_7fd6b7         8.316138
2603  seg_0b07c7         8.365514
2604  seg_fdc1d4         8.305465
2605  seg_d56d32         8.095241
2606  seg_31631c         7.761644
2607  seg_d5b100         7.834221
2608  seg_397983         8.153612
2609  seg_507065         8.369188
2610  seg_ec4645         8.211747
2611  seg_1a0eca         8.332183
2612  seg_d5f344         7.524226
2613  seg_87f6c8         8.395706
2614  seg_9d57a1         8.244791
2615  seg_7cb417         8.376235
2616  seg_00184e         8.398927
2617  seg_6d01a3         8.373042
2618  seg_e40348         8.395774
2619  seg_d36681         8.395555
2620  seg_c24946         7.753196
2621  seg_482745         8.000614
2622  seg_e8ad6b         8.100733
2623  seg_2f9581         6.466939

[2624 rows x 2 columns]

In [17]:
res.to_csv('./data/submission.csv', index=False)